---
kind: pipeline
name: build-armhf

platform:
  os: linux
  arch: amd64

steps:
- name: make
  image: 233704588990.dkr.ecr.ap-northeast-1.amazonaws.com/ci/docker:stretch
  commands:
  - make build
  - make mpkg
  environment:
    ARCH: armhf
  volumes:
  - name: docker
    path: /var/run/docker.sock
  - name: docker-token
    path: /root/.docker/config.json
  when:
    event:
    - push

- name: upload
  image: 233704588990.dkr.ecr.ap-northeast-1.amazonaws.com/ci/awscli:latest
  commands:
  - "aws s3 cp $${ASSETS_TARGET} $${S3_TARGET} --recursive --exclude \"*\" --include \"*.mpkg\""
  environment:
    ASSETS_TARGET: app
    S3_TARGET: "s3://moxaics/v3/edge/builds/${DRONE_REPO_NAME}/${DRONE_BRANCH}/${DRONE_BUILD_NUMBER}"
  when:
    event:
    - push

- name: upload-openapi
  image: 233704588990.dkr.ecr.ap-northeast-1.amazonaws.com/ci/awscli:latest
  commands:
  - "aws s3 cp $${ASSETS_TARGET} $${S3_TARGET} --recursive"
  environment:
    ASSETS_TARGET: openapi
    S3_TARGET: "s3://moxaics/v3/edge/builds/${DRONE_REPO_NAME}/${DRONE_BRANCH}/${DRONE_BUILD_NUMBER}/openapi"
  when:
    event:
    - push

- name: upload-to-stable
  image: 233704588990.dkr.ecr.ap-northeast-1.amazonaws.com/ci/awscli:latest
  commands:
  - "aws s3 cp $${S3_SOURCE} $${S3_TARGET} --recursive"
  environment:
    S3_SOURCE: "s3://moxaics/v3/edge/builds/${DRONE_REPO_NAME}/${DRONE_BRANCH}/${CI_PARENT_BUILD_NUMBER}"
    S3_TARGET: "s3://moxaics/v3/edge/stable/${DRONE_REPO_NAME}/${CI_PARENT_BUILD_NUMBER}"
  when:
    event:
    - promote

volumes:
- name: docker
  host:
    path: /var/run/docker.sock
- name: docker-token
  host:
    path: /root/.docker/config.json

...
