version: '2'
services:
  server:
    image: moxaics/wifiap:${VERSION}-${ARCH}
    entrypoint: ["/usr/local/bin/server"]
    privileged: true
    network_mode: "host"
    volumes:
      - /lib/firmware:/lib/firmware:ro
