version: '2'
services:
  server:
    image: moxaics/wifiap:0.0.1-armhf
    entrypoint: ["/usr/local/bin/server"]
    privileged: true
    network_mode: "host"
    volumes:
      - /lib/firmware:/lib/firmware:ro
